# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

orbs:
   slack: circleci/slack@4.2.0
   
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      # - image: redis:2.8.19
    steps:
      - checkout
      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo apt-get install jq curl
      - run:
          name: Run semantic-versioning
          command: |
              npm install @semantic-release/changelog
              npm install @semantic-release/git
              npx semantic-release --branches $CIRCLE_BRANCH
      - run:
          name: Export dot env variable to .env_test file
          command: | 
            printenv | grep TESTENV_ | sed 's/^\(TESTENV_\)*//' >> .env_test
      - run:
          name: Export custom slack template
          command: echo 'export MY_ORB_TEMPLATE=$(cat .circleci/slack_template.json)' >> $BASH_ENV
      - slack/notify:
          event: always
          channel: "legal-monitoring"
          template: MY_ORB_TEMPLATE 
 
workflows:
  version: 2.1
  build-stage:
    jobs:
      - build:
          context:
             - gitflow-staging
             - slack-secrets
