version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"
jobs:
  my-job:
    machine:
       image: ubuntu-2004:202101-01
    steps:
      - greeting:
          to: "Ven"
      - run: 
           name: saving build number in variable
           command: |
              echo job_id=$CIRCLE_BUILD_NUM
  job-status:
    machine:
       image: ubuntu-2004:202101-01
    steps:
      - run:
          name: API call to deploy job
          command: |
              curl --request GET \
               --url https://circleci.com/api/v2/project/github/Ven2575/gitflow-demo/job/$job_id \
               --header 'authorization: Basic REPLACE_BASIC_AUTH' >> apioutput.json
      - run:
           name: finding job status
           command: |
              echo '
              #!/bin/bash/
              OUTPUT=$(grep "success" ~/project/apioutput.json)
              
              if [ -n "${OUTPUT}" ]; then
                     echo "${OUTPUT}"
                 else
                     echo "Job is failed"
               fi' >> jobstatus.sh
      - run: 
        
            name: Finding the job status
            command: |
               sh ~/project/jobstatus.sh
               
workflows:
  my-workflow:
    jobs:
      - my-job
      - job-status:
           requires:
              - my-job
