version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"
jobs:
  my-job:
    machine:
       image: ubuntu-2004:202101-01
    steps:
      - greeting:
          to: "Ven"
      - run:
          name: API call to deploy job
          command: |
              curl --request GET \
               --url https://circleci.com/api/v2/project/github/Ven2575/gitflow-demo/job/$CIRCLE_BUILD_NUM \
               --header 'authorization: Basic REPLACE_BASIC_AUTH' >> apioutput.json
      - run:
           name: finding job status
           command: |
              echo 'export OUTPUT=$(grep "success" ~/project/apioutput.json)' >> $BASH_ENV
              
              if [ -n "${OUTPUT}"]; then
                    echo "$OUTPUT"
                  else
                     echo "Job is failed"
               fi
               
workflows:
  my-workflow:
    jobs:
      - my-job        
