version: 2.1

parameters:
  rollback_job:
    type: boolean
    default: false      
      
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:

      - run: "build job"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
              --header 'Content-Type: application/json' \
              -u "${CIRCLE_TOKEN}:" \
              -d '{
                            "parameters": {
                              "rollback_job": true
                            }
                          }'
     
          when: on_fail       
   

               
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "test job"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
              --header 'Content-Type: application/json' \
              -u "${CIRCLE_TOKEN}:" \
              -d '{
                            "parameters": {
                              "rollback_job": true
                            }
                          }'
     
          when: on_fail       

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "deploy"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/:vcs/:org/:repo/pipeline' \
              --header 'Content-Type: application/json' \
              -u "${CIRCLE_TOKEN}:" \
              -d '{
                            "parameters": {
                              "rollback_job": true
                            }
                          }'
     
          when: on_fail       
  rollback:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "running rollback job"      
      
            
      
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test     
  rollback_workflow:
    when: << pipeline.parameters.rollback_job >>
    jobs:
      - rollback 
