version: 2.1      
      
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:

      - run: echo "build job" 
  test:
    machine:
       image: ubuntu-2004:202101-01
    steps:
      - run: echo "test job"       
      
  deploy:
    machine:
       image: ubuntu-2004:202101-01
    steps:
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
             ssh-keyscan 94.130.12.67 >> ~/.ssh/known_hosts # Add staging server IP to known hosts
      - add_ssh_keys:
          fingerprints:
            - "4e:80:2e:d7:16:88:03:b3:43:ee:15:bf:3e:c1:5b:05"
      - run: echo "deploy"
      - run:
          name: symlink to new version
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd /var/www/clients/client1/web16/web && ln -sf /var/www/clients/client1/web16/web/new/ public'
          when: on_success
      - run:
          name: symlink to old version
          command: |
            ssh $SSH_USER@$SSH_HOST 'cd /var/www/clients/client1/web16/web && unlink public && ln -sf /var/www/clients/client1/web16/web/old/ public'
          when: on_failure
            
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test    
 
