version: 2.1

parameters:
  run_workflow_rollback_job:
    type: boolean
    default: false      
      
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:

      - run: "build job"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/github/Ven2575/gitflow-demo/pipeline' \
              --header 'Content-Type: application/json' \
              --header 'Circle-Token: 4ba4c16b93e6e3999938690200ec4d2c5d52ee8e' \
              -d '{ 
                            "branch": "feature/rollback-spike" ,
                            "parameters": {
                              "run_workflow_rollback_job": true
                            }
                          }'
               echo "parameter value is << pipeline.parameters.run_workflow_rollback_job >> "
          when: on_fail       
          ##"branch": "feature/rollback-spike" 
  test:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "test job"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/github/Ven2575/gitflow-demo/pipeline' \
              --header 'Content-Type: application/json' \
              --header 'Circle-Token: 4ba4c16b93e6e3999938690200ec4d2c5d52ee8e' \
              -d '{
                            #"branch": "feature/rollback-spike", 
                            "parameters": {
                              "run_workflow_rollback_job": true
                            }
                          }'
     
          when: on_fail       

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "deploy"
      - run: 
          name: run rollback job
          command: |
              curl --location --request POST 'https://circleci.com/api/v2/project/github/Ven2575/gitflow-demo/pipeline' \
              --header 'Content-Type: application/json' \
              --header 'Circle-Token: 4ba4c16b93e6e3999938690200ec4d2c5d52ee8e' \
              -d '{
                            #"branch": "feature/rollback-spike",
                            "parameters": {
                              "run_workflow_rollback_job": true
                            }
                          }'
     
          when: on_fail       
  rollback:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "running rollback job"      
      
            
      
workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test     
  rollback_workflow:
    when: << pipeline.parameters.run_workflow_rollback_job >>
    jobs:
      - rollback
 
